name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Install all dependencies including devDependencies. Tailwind and PostCSS
      # are defined as devDependencies and must be installed for the build.
      - name: Install dependencies
        run: npm ci

      - name: Build and Export
        run: |
          npm run build
        env:
          # Ensure NODE_ENV is not set to production during install so dev deps are available.
          # It can remain undefined here.
          NEXT_TELEMETRY_DISABLED: '1'

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4